name: deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16.14.x
        cache: npm
    - name: Install
      run: npm install
    - name: Build
      run: npm run build
    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
        HOST: ${{ secrets.SSH_SERVER }}
        PORT: ${{ secrets.SSH_PORT }}
        USERNAME: ${{ secrets.SSH_USERNAME }}
        PASSWORD: ${{ secrets.SSH_PASSWORD }}
        source: ./dist/resume-viewer/*
        target: ./andreas.pieger.online
